- shell: "ethermint --datadir /etc/ethermint unsafe_reset_all"
  when: "service == 'ethermint'"
  become_user: ethermint

- command: "{{service}} node unsafe_reset_all --home=/etc/{{service}}"
  become_user: "{{service}}"

- file: "path=/etc/{{service}}/config/addrbook.json state=absent"


