---

#Three commands to install a service on CentOS/RedHat
#wget -O - https://tendermint-packages.interblock.io/centos/7/os/x86_64/RPM-GPG-KEY-Tendermint | rpm --import -
#wget -O /etc/yum.repos.d/tendermint.repo https://tendermint-packages.interblock.io/centos/7/os/x86_64/tendermint.repo
#yum update && yum install basecoin

#This has a bug in Ansible 2.3: https://github.com/ansible/ansible/issues/20711
#- name: Add repository key on CentOS/RedHat
#  when: ansible_os_family == "RedHat"
#  rpm_key: key=https://tendermint-packages.interblock.io/centos/7/os/x86_64/RPM-GPG-KEY-Tendermint

#Workaround
- name: Download repository key for CentOS/RedHat
  when: ansible_os_family == "RedHat"
  get_url: "url=https://tendermint-packages.interblock.io/{{ (devops_path | default(false) | bool) | ternary('devops/','') }}centos/7/os/x86_64/RPM-GPG-KEY-Tendermint dest=/root/RPM-GPG-KEY-Tendermint force=yes checksum=sha256:a8c61d4061697d2595562c703dbafbdfdcfa7f0c75a523ac84d5609d1b444abe"
- name: Import repository key for CentOS/RedHat
  when: ansible_os_family == "RedHat"
  command: "rpm --import /root/RPM-GPG-KEY-Tendermint"

- name: Install tendermint repository on CentOS/RedHat
  when: ansible_os_family == "RedHat"
  yum_repository:
    name: tendermint
    baseurl: https://tendermint-packages.interblock.io/{{ (devops_path | default(false) | bool) | ternary('devops/','') }}centos/7/os/x86_64
    description: "Tendermint repo"
    gpgcheck: yes
    gpgkey: https://tendermint-packages.interblock.io/{{ (devops_path | default(false) | bool) | ternary('devops/','') }}centos/7/os/x86_64/RPM-GPG-KEY-Tendermint
#    repo_gpgcheck: yes

- name: Install package on CentOS/RedHat
  when: ansible_os_family == "RedHat"
  yum: "pkg={{service}} update_cache=yes state=latest"

# The below commands are required so that the tomlconfig playbook can run.

- name: Install epel-release on CentOS/RedHat
  when: ansible_os_family == "RedHat"
  yum: "pkg=epel-release update_cache=yes state=latest"

- name: Install pip on CentOS/RedHat
  when: ansible_os_family == "RedHat"
  yum: "pkg={{item}} state=latest"
  with_items:
  - python2-pip
  - python-virtualenv
  - unzip
  - tar
#For show_validator command:
  - tendermint

- name: Install toml 
  when: ansible_os_family == "RedHat"
  pip: name=toml

