---

#Three commands to install a service on Debian/Ubuntu
#wget -O - https://tendermint-packages.interblock.io/centos/7/os/x86_64/RPM-GPG-KEY-Tendermint | apt-key add -
#wget -O /etc/apt/sources.list.d/tendermint.list https://tendermint-packages.interblock.io/debian/tendermint.list
#apt-get update && apt-get install basecoin

- name: Add repository key on Debian/Ubuntu
  when: ansible_os_family == "Debian"
  apt_key:
    url: https://tendermint-packages.interblock.io/{{ (devops_path | default(false) | bool) | ternary('devops/','') }}centos/7/os/x86_64/RPM-GPG-KEY-Tendermint
    id: 2122CBE9

- name: Install tendermint repository on Debian/Ubuntu
  when: ansible_os_family == "Debian"
  apt_repository:
    repo: deb https://tendermint-packages.interblock.io/{{ (devops_path | default(false) | bool) | ternary('devops/','') }}debian stable main

- name: Install package on Debian/Ubuntu
  when: ansible_os_family == "Debian"
  apt: "pkg={{service}} update_cache=yes state=latest"

# The below command is required to use the tomlconfig playbook.

- name: Install package on Debian/Ubuntu
  when: ansible_os_family == "Debian"
  apt: "pkg={{item}} state=latest"
  with_items:
  - python-toml
  - unzip
  - tar
#For show_validator command:
  - tendermint

