---
tendermint_user: tendermint
tendermint_group: tendermint
tendermint_home: /var/lib/tendermint

basecoin_user: basecoin
basecoin_group: basecoin
basecoin_home: /var/lib/basecoin
basecoin_inprocess: false

testnet_name: testnet1
dev_money: false
